name: Automated Test for R
# Action for GitHub
on: ["push", "pull_request"]

# The job to Run
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.0', '3.6']

    steps:
    - uses: actions/checkout@v2
    - name: Set up R ${{ matrix.R-version }}
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.r-version }}
    - run: Rscript -e 'install.packages("testthat"); testthat::test_dir("./tests/testthat/")'